name: Convert Markdown to HTML
on:
push:
branches:
- main
- master
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Set up Go
uses: actions/setup-go@v2
with:
go-version: '^1.16'
- name: Install dependencies
run: go get github.com/russross/blackfriday/v2
- name: Convert Markdown to HTML
run: go run ./src/convert_md_2_html.go
- name: Commit files
run: |
#git config --local user.email "action@github.com"
#git config --local user.name "GitHub Action"
#git add -A
#git commit -m "Convert Markdown to HTML" -a || echo "No changes to commit"
#git push
